### ISSUE TITLE
Units sent from Scio app to remote server are incorrect

### ISSUE THREAD

**Issue by crenshaw** [crenshaw/sensor_hive#34]
Currently, the Scio app sends the remote server that ports 1 - 5 are in "Degrees" and port 6 is in "Degrees".  I'd like to change the former to "Celcius" and the latter to "Lux".

**Comment by nwarlen** [comment]
Unable to test changes as I have no hardware but this should work: https://github.com/crenshaw/sensor_hive/pull/36

If the changes work properly, feel free to merge and close the PR.

**Comment by epaulson10** [comment]
I have the units fixed in one of my branches. I think we forgot to merge
the changes because the semester ended and we got busy with other stuff.
I'll look at it tomorrow.
